version: "3.9"

services:
 
  rabbit:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=msociety
      - RABBITMQ_DEFAULT_PASS=msociety
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbit:/var/lib/rabbitmq
    logging:
      driver: none

  mongodb:
    image : mongo
    volumes:
      - ./mongo:/data/db
    logging:
      driver: none

  account_service:
    build: ./AccountService
    volumes:
      - ./AccountService:/app
    depends_on:
      - rabbit
    
  blog_write_service:
    build: ./BlogWriteService
    volumes:
      - ./BlogWriteService:/app
    depends_on:
      - rabbit
  
  blog_read_service:
    build: ./BlogReadService
    volumes:
      - ./BlogReadService:/app
    depends_on:
      - mongodb
      - rabbit
    
  email_service:
    build: ./EmailService
    volumes:
      - ./EmailService:/app
    depends_on:
      - rabbit

  gateway:
    image: nginx:latest
    volumes:
      - ./utils/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./AccountService/media/profile_pics:/var/microsociety/media/profile_pics
      - ./BlogWriteService/media/post_pics:/var/microsociety/media/post_pics
    depends_on:
      - account_service
      - blog_write_service
      - blog_read_service
      - email_service
    ports:
      - "8000:8000"